# Generated by Django 4.2.4 on 2023-10-31 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('oldprice', models.IntegerField(null=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('images', models.ImageField(upload_to='photos/products')),
                ('stock', models.IntegerField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('front_image', models.ImageField(blank=True, upload_to='photos/products')),
                ('top_image', models.ImageField(blank=True, upload_to='photos/products')),
            ],
        ),
    ]
