# Generated by Django 4.2.4 on 2023-11-24 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_product_stock_product_is_seasonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount_percentage', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounted_products', to='adminapp.seasonaloffer'),
        ),
    ]
