# Generated by Django 4.2.4 on 2023-11-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_seasonaloffer_product_seasonal_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='offer_banner1',
            field=models.ImageField(blank=True, upload_to='photos/banners'),
        ),
        migrations.AddField(
            model_name='banner',
            name='offer_banner2',
            field=models.ImageField(blank=True, upload_to='photos/banners'),
        ),
    ]
