# Generated by Django 4.2.4 on 2023-11-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_banner_offer_banner1_banner_offer_banner2'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='offer_banner3',
            field=models.ImageField(blank=True, upload_to='photos/banners'),
        ),
    ]
