# Generated by Django 4.2.4 on 2023-12-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_banner_offer_banner3'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, upload_to='photos/category'),
        ),
    ]
