# Generated by Django 4.2.4 on 2023-12-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_category_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='banner',
            new_name='banner1',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner2',
            field=models.ImageField(blank=True, upload_to='photos/banners'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner3',
            field=models.ImageField(blank=True, upload_to='photos/banners'),
        ),
    ]
