# Generated by Django 4.2.4 on 2023-11-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='product_price',
        ),
    ]
