# Generated by Django 4.2.4 on 2023-11-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_remove_orderitems_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
