# Generated by Django 4.2.4 on 2023-11-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
