# Generated by Django 4.2.4 on 2023-11-24 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_seasonaloffer_product_seasonal_offer'),
        ('storeapp', '0011_cartitem_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.product'),
        ),
    ]
