# Generated by Django 4.2.4 on 2023-11-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0014_alter_cartitem_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
