# Generated by Django 4.2.4 on 2023-12-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0018_remove_coupon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
