# Generated by Django 4.2.4 on 2023-12-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0021_remove_coupon_used_by_coupon_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='used',
        ),
    ]
