# Generated by Django 4.2.4 on 2023-11-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0002_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
