# Generated by Django 4.2.4 on 2023-11-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0005_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cropped_profile_pic',
            field=models.ImageField(blank=True, default='default_cropped.jpg', null=True, upload_to='cropped_profile_pics/'),
        ),
    ]
