# Generated by Django 4.2.4 on 2023-12-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0008_customuser_referral_code_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
